
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ice_pomelo
      MYSQL_DATABASE: ice_pomelo
      MYSQL_USER: ice_pomelo
      MYSQL_PASSWORD: ice_pomelo
    ports:
      - "3306:3306"
    networks:
      - ice_pomelo
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=ice_pomelo
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "6379:6379"
    networks:
      - ice_pomelo

  etcd:
    container_name: etcd
    image: "quay.io/coreos/etcd:v3.5.5"
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_API=3
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./data/etcd:/etcd-data
    networks:

      - ice_pomelo
networks:
  ice_pomelo:
    driver: bridge
