// Code generated by Kitex v0.8.0. DO NOT EDIT.

package tinyidservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	tiny_id "github.com/jiuxia211/ice-pomelo/kitex_gen/tiny_id"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetMaxID(ctx context.Context, req *tiny_id.GetMaxIDRequest, callOptions ...callopt.Option) (r *tiny_id.GetMaxIDResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTinyIDServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTinyIDServiceClient struct {
	*kClient
}

func (p *kTinyIDServiceClient) GetMaxID(ctx context.Context, req *tiny_id.GetMaxIDRequest, callOptions ...callopt.Option) (r *tiny_id.GetMaxIDResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMaxID(ctx, req)
}
