// Code generated by Kitex v0.8.0. DO NOT EDIT.

package tinyidservice

import (
	server "github.com/cloudwego/kitex/server"
	tiny_id "github.com/jiuxia211/ice-pomelo/kitex_gen/tiny_id"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler tiny_id.TinyIDService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
