// Code generated by Kitex v0.8.0. DO NOT EDIT.
package tinyidservice

import (
	server "github.com/cloudwego/kitex/server"
	tiny_id "github.com/jiuxia211/ice-pomelo/kitex_gen/tiny_id"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler tiny_id.TinyIDService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
