// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/jiuxia211/ice-pomelo/cmd/api/biz/rpc"
	"github.com/jiuxia211/ice-pomelo/config"
)

func main() {
	klog.SetLevel(klog.LevelDebug)
	hlog.SetLevel(hlog.LevelDebug)
	config.Init()
	rpc.Init()

	h := server.Default()

	register(h)
	h.Spin()
}
