// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/kitex/pkg/klog"
	"github.com/jiuxia211/ice-pomelo/cmd/api/biz/rpc"
	"github.com/jiuxia211/ice-pomelo/cmd/api/biz/ws"
	"github.com/jiuxia211/ice-pomelo/cmd/api/biz/ws/db"
	"github.com/jiuxia211/ice-pomelo/config"
)

func wsInit() {
	db.Init()
	go ws.Manager.Start()
}

func main() {
	klog.SetLevel(klog.LevelDebug)
	hlog.SetLevel(hlog.LevelDebug)
	config.Init()
	rpc.Init()

	h := server.New(
		server.WithMaxRequestBodySize(20*1024*1024),
		server.WithHostPorts("127.0.0.1:8888"),
		server.WithMaxRequestBodySize(400*1024*1024))

	h.NoHijackConnPool = true
	register(h)
	wsInit()
	h.Spin()
}
